version: '3.7'

x-env-defaults: &env
  APPLICATION_URL: ${APPLICATION_URL-http://0.0.0.0:12002}
  APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL-http://application}
  EXPORT_SERVICE_URL: ${EXPORT_SERVICE_URL-http://export}
  LOCALE_SERVICE_URL: ${LOCALE_SERVICE_URL-http://locale}
  MAILER_SERVICE_URL: ${MAILER_SERVICE_URL-http://mailer}
  MEMBERSHIP_SERVICE_URL: ${MEMBERSHIP_SERVICE_URL-http://membership}
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017/identity-x}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  ORGANIZATION_SERVICE_URL: ${ORGANIZATION_SERVICE_URL-http://organization}
  SENDING_DOMAIN: ${SENDING_DOMAIN-identity-x.base-cms.io}
  TOKEN_SERVICE_URL: ${TOKEN_SERVICE_URL-http://token}
  SUPPORT_EMAIl: ${SUPPORT_EMAIL-root@localhost}
  SUPPORT_ENTITY: ${SUPPORT_ENTITY-My Dev Company}
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  USER_SERVICE_URL: ${USER_SERVICE_URL-http://user}
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  working_dir: /identity-x
  restart: always
  volumes:
    - .:/identity-x:cached
    - ./node_modules:/identity-x/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "12000:27017"

  graphql:
    <<: *node
    working_dir: /identity-x/services/graphql
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12001
    depends_on:
      - application
      - export
      - locale
      - membership
      - organization
      - user
    ports:
      - "12001:80"

  manage:
    <<: *node
    image: danlynn/ember-cli:3.10.1
    working_dir: /identity-x/services/manage
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--port", "12002", "--proxy", "http://graphql"]
    tmpfs:
      - /identity-x/services/manage/tmp
    depends_on:
      - graphql
    ports:
      - "12002:12002"

  organization:
    <<: *node
    working_dir: /identity-x/services/organization
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    depends_on:
      - mongodb
    ports:
      - "12003:80"

  token:
    <<: *node
    working_dir: /identity-x/services/token
    command: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12004
      TOKEN_SECRET: ${TOKEN_SECRET-thisisntverysecret}
    depends_on:
      - mongodb
    ports:
      - "12004:80"

  mailer:
    <<: *node
    working_dir: /identity-x/services/mailer
    command: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12005
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - "12005:80"

  user:
    <<: *node
    working_dir: /identity-x/services/user
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    depends_on:
      - mongodb
      - token
      - mailer
    ports:
      - "12006:80"

  membership:
    <<: *node
    working_dir: /identity-x/services/membership
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    depends_on:
      - mailer
      - mongodb
      - organization
      - token
      - user
    ports:
      - "12007:80"

  application:
    <<: *node
    working_dir: /identity-x/services/application
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    depends_on:
      - ip
      - locale
      - mongodb
      - token
      - organization
    ports:
      - "12008:80"

  locale:
    <<: *node
    working_dir: /identity-x/services/locale
    command: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12009
    ports:
      - "12009:80"

  ip:
    <<: *node
    working_dir: /identity-x/services/ip
    command: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 12010
    ports:
      - "12010:80"

  export:
    <<: *node
    working_dir: /identity-x/services/export
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent"]
    depends_on:
      - application
      - mailer
    ports:
      - "12011:80"

    environment:
      <<: *env
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
  mongodb: {}
  yarn-cache: {}
